#import "@preview/elembic:1.1.1" as e: field, types

// Here we crudely construct an inspectable enum type
#let base-colors = (
  "RED",
  "ORANGE",
  "YELLOW",
  "GREEN",
  "BLUE",
  "INDIGO",
  "PURPLE",
)
#let ergo-base-color = types.union(..base-colors)
#let ergo-base-colors = (:)
#for base-color in base-colors {
  ergo-base-colors.insert(base-color, base-color)
}

// base color > ergo box color scheme

#let ergo-color-scheme = types.declare(
  "ergo-color-scheme",
  prefix: "@preview/ergo:0.3.0",
  doc: "Base 16 color scheme, for use with Ergo.",
  fields: (
    field("is-light",   bool,  doc: "Whether the color scheme is light.", required: true),
    field("PRIMARY1",   color, doc: "Primary color 1",                    required: true),
    field("PRIMARY2",   color, doc: "Primary color 2",                    required: true),
    field("PRIMARY3",   color, doc: "Primary color 3",                    required: true),
    field("SECONDARY1", color, doc: "Secondary color 1",                  required: true),
    field("SECONDARY2", color, doc: "Secondary color 2",                  required: true),
    field("SECONDARY3", color, doc: "Secondary color 3",                  required: true),
    field("RED",        color, doc: "Red",                                required: true),
    field("ORANGE",     color, doc: "Orange",                             required: true),
    field("YELLOW",     color, doc: "Yellow",                             required: true),
    field("GREEN",      color, doc: "Green",                              required: true),
    field("BLUE",       color, doc: "Blue",                               required: true),
    field("INDIGO",     color, doc: "Indigo",                             required: true),
    field("PURPLE",     color, doc: "Purple",                             required: true),
    field("HIGHLIGHT",  color, doc: "Highlight",                          required: true),
  )
)

#let get-document-theming(color-scheme) = {
  assert(types.is(color-scheme, ergo-color-scheme))

  let fill-color = color-scheme.PRIMARY1
  fill-color = if color-scheme.is-light { fill-color.lighten(15%) } else { fill-color.darken(15%) }

  let strong-color = color-scheme.HIGHLIGHT
  strong-color = if color-scheme.is-light { strong-color.darken(60%) } else { strong-color.lighten(60%) }

  (
    fill:   fill-color,
    text1:  color-scheme.SECONDARY2,
    text2:  color-scheme.SECONDARY3,
    h1:     color-scheme.SECONDARY3,
    h2:     color-scheme.SECONDARY1,
    strong: strong-color,
  )
}

#let color-scheme-names = read("./valid-schemes.txt").trim().split("\n") // generated by script
#let ergo-color-schemes = (:)

// Initialize colors
#for color-scheme-name in color-scheme-names {
  ergo-color-schemes.insert(color-scheme-name, json("templates/" + color-scheme-name + ".json"))
}

// Calculates raw ratio based on float
#let get-ratio(colors, env-name, parameter-name) = {
  return float(colors.at(env-name).at(parameter-name)) * 100%
}

// Returns color dict of associated environment
#let get-colors(colors, env-name) = {
  return colors.at(env-name, default: none)
}
