#import "@preview/elembic:1.1.1" as e: field, types

// Here we crudely construct an inspectable enum type
#let base-colors = (
  "RED",
  "ORANGE",
  "YELLOW",
  "GREEN",
  "BLUE",
  "INDIGO",
  "PURPLE",
)
#let ergo-base-color = types.union(..base-colors)
#let ergo-base-colors = (:)
#for base-color in base-colors {
  ergo-base-colors.insert(base-color, base-color)
}

// base color > ergo box color scheme

// TODO allow dictionary casting
#let ergo-color-scheme = types.declare(
  "ergo-color-scheme",
  prefix: "@preview/ergo:0.3.0",
  doc: "Base 16 color scheme, for use with Ergo.",
  fields: (
    field("is-light",   bool,  doc: "Whether the color scheme is light.", required: true),
    field("PRIMARY1",   color, doc: "Primary color 1",                    required: true),
    field("PRIMARY2",   color, doc: "Primary color 2",                    required: true),
    field("PRIMARY3",   color, doc: "Primary color 3",                    required: true),
    field("SECONDARY1", color, doc: "Secondary color 1",                  required: true),
    field("SECONDARY2", color, doc: "Secondary color 2",                  required: true),
    field("SECONDARY3", color, doc: "Secondary color 3",                  required: true),
    field("RED",        color, doc: "Red",                                required: true),
    field("ORANGE",     color, doc: "Orange",                             required: true),
    field("YELLOW",     color, doc: "Yellow",                             required: true),
    field("GREEN",      color, doc: "Green",                              required: true),
    field("BLUE",       color, doc: "Blue",                               required: true),
    field("INDIGO",     color, doc: "Indigo",                             required: true),
    field("PURPLE",     color, doc: "Purple",                             required: true),
    field("HIGHLIGHT",  color, doc: "Highlight",                          required: true),
  )
)

#let document-theming = types.declare(
  "document-theming",
  prefix: "@preview/ergo:0.3.0",
  doc: "Colors to be used for theming the entire document, and individual ergo-boxes.",
  fields: (
    field("fill",   color, doc: "The fill color of the page.",            required: true),
    field("text1",  color, doc: "The fill color of ordinary text.",       required: true),
    field("text2",  color, doc: "The fill color of ergo-box title text.", required: true),
    field("h1",     color, doc: "The fill color used for header 1s.",     required: true),
    field("h2",     color, doc: "The fill color used for header 2s.",     required: true),
    field("strong", color, doc: "The fill color used for bold text.",     required: true)
  )
)

#let environment-theming = types.declare(
  "environment-theming",
  prefix: "@preview/ergo:0.3.0",
  doc: "Background colors to be used in the ergo box environment.",
  fields: (
    field("bgcolor1",     color, doc: "The main background color.", required: true),
    field("bgcolor2",     color, doc: "The background color for the solution.", required: true),
    field("strokecolor1", color, doc: "The background color for the title.", required: true),
    field("strokecolor2", color, doc: "The ", required: true),  // TODO: finish this
  )
)

#let get-document-theming(color-scheme) = {
  assert(types.is(color-scheme, ergo-color-scheme))

  let fill-color = color-scheme.PRIMARY1
  fill-color = if color-scheme.is-light { fill-color.lighten(15%) } else { fill-color.darken(15%) }

  let strong-color = color-scheme.HIGHLIGHT
  strong-color = if color-scheme.is-light { strong-color.darken(60%) } else { strong-color.lighten(60%) }

  return e.types.cast((
    fill:   fill-color,
    text1:  color-scheme.SECONDARY2,
    text2:  color-scheme.SECONDARY3,
    h1:     color-scheme.SECONDARY3,
    h2:     color-scheme.SECONDARY1,
    strong: strong-color,
  ), document-theming)
}

#let color-scheme-names = read("./valid-schemes.txt").trim().split("\n") // generated by script
#let ergo-color-schemes = (:)

// Initialize colors
#for color-scheme-name in color-scheme-names {
  ergo-color-schemes.insert(
    color-scheme-name,
    types.cast(
      json("templates/" + color-scheme-name + ".json"),
      ergo-color-scheme,
    )
  )
}

#let get-env-colors(color-scheme, base-color) = {

}

// Calculates raw ratio based on float
#let get-ratio(colors, env-name, parameter-name) = {
  return float(colors.at(env-name).at(parameter-name)) * 100%
}
